# command line: main.py demo_offline --video resource/media/ta_chi.mp4

config: ./config/st_gcn/custom_set/demo_offline.yaml
device:
- 0
height: 1080
ignore_weights: []
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 3
model_fps: 30
model_input_frame: 128
openpose: ./openpose
print_log: false
save_log: true
use_gpu: true
video: resource/media/ta_chi.mp4
weights: ./models/actionRecognitionModel.pt
work_dir: ./work_dir/tmp
